language: python
python:
  - 3.7.5
install:
  - pip install -r requirements.txt

jobs:
  include:
      - stage: test
        script: pytest server/test_gamemanager.py
      - stage: mutation
        script: cd server && mut.py --target GameManager --unit-test test_mutation -m && cd ..

