language: python
os:
  osx
# python:
#   - 3.5.4

# matrix:
#   include:
#         - python: 3.5
#           dist: trusty
#           sudo: false
install:
  - pip install -r requirements.txt
script:

  pytest server/test_query.py 